"""phase0 init: strategy_runs signals positions journal

Revision ID: e5219b17f156
Revises: 
Create Date: 2026-05-28 19:36:29.980061
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e5219b17f156'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_size', sa.Integer(), nullable=False),
    sa.Column('entry_score', sa.Float(), nullable=True),
    sa.Column('reason_topdown', sa.Text(), nullable=True),
    sa.Column('reason_bottomup', sa.Text(), nullable=True),
    sa.Column('reason_catalyst', sa.Text(), nullable=True),
    sa.Column('reason_timing', sa.Text(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('hold_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_trades_exit_date'), 'journal_trades', ['exit_date'], unique=False)
    op.create_index(op.f('ix_journal_trades_symbol'), 'journal_trades', ['symbol'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('strategy_kind', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('market_gate', sa.Boolean(), nullable=True),
    sa.Column('market_gate_msg', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date', 'strategy_name', 'market', name='uq_run_date_strategy_market')
    )
    op.create_index(op.f('ix_strategy_runs_run_date'), 'strategy_runs', ['run_date'], unique=False)
    op.create_table('journal_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('risk_flag', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['journal_trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_snapshots_trade_id'), 'journal_snapshots', ['trade_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('hold_days', sa.Integer(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_run_id'), 'positions', ['run_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_run_id'), 'signals', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_run_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_positions_run_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_journal_snapshots_trade_id'), table_name='journal_snapshots')
    op.drop_table('journal_snapshots')
    op.drop_index(op.f('ix_strategy_runs_run_date'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index(op.f('ix_journal_trades_symbol'), table_name='journal_trades')
    op.drop_index(op.f('ix_journal_trades_exit_date'), table_name='journal_trades')
    op.drop_table('journal_trades')
    # ### end Alembic commands ###
